TestAplication1/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace TestAplication1.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
    }
}

TestAplication1/Models/UserContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TestAplication1.Models
{
    public class UserContext : DbContext
    {
        public DbSet<User> Users { get; set; }
    }
}

TestAplication1/Models/UserDbInitializer.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TestAplication1.Models
{
    public class UserDbInitializer : DropCreateDatabaseAlways<UserContext>
    {
        protected override void Seed(UserContext db)
        {
            var users = db.Users;
            for (int i = 1; i <= 10; i++)
            {
                users.Add(new User { Name = "User"+i, Mail = "User"+i+"@mail.ru" });
            }
            base.Seed(db);
        }
    }
}

TestAplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestAplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TestAplication1/Controllers/UserManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web.Mvc;
using TestAplication1.Models;

namespace TestAplication1.Controllers
{
    public class UserManagerController : Controller
    {
        private readonly UserContext _db = new UserContext();

        // GET: Users
        public ActionResult Users()
        {
            IEnumerable<User> users = _db.Users;
            ViewBag.Users = users;
            return View();
        }

        [HttpGet]
        public ActionResult UserEdit(int id = 1)
        {
            var countUser = _db.Users.Count();
            if (countUser == 0)
            {
                return Redirect("/UserManager/UserAdd");
            }
            ViewBag.UserCount = countUser;
            var user = _db.Users.Find(id);
            return View(user);
        }

        [HttpPost]
        public ActionResult UserEdit(User newUser)
        {
            var user = _db.Users.FirstOrDefault(u => u.Id == newUser.Id);
            user.Name = newUser.Name;
            user.Mail = newUser.Mail;
            _db.SaveChanges();
            ViewBag.Status = "Сохранено успешно!!!";
            return UserEdit(user.Id);
        }

        public ActionResult UserAdd()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UserAdd(User user)
        {
            _db.Users.Add(user);
            _db.SaveChanges();
            ViewBag.Status = "Добавлен успешно!!!";
            return View();
        }
    }
}

TestAplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Список пользователей", "Users", "UserManager", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Редактирование пользователей", "UserEdit", "UserManager")</li>
                    <li>@Html.ActionLink("Добавление пользователей", "UserAdd", "UserManager")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TestAplication1/Views/UserManager/UserAdd.cshtml
@{
    
}
<div>
    <h3>Добавление пользователя</h3>
    <form method="post" action="">
        <table>
            <tr>
                <td><p>Имя:</p></td>
                <td><input type="text" name="Name" /> </td>
            </tr>
            <tr>
                <td><p>Почта:</p></td>
                <td>
                    <input type="text" name="Mail"/>
                </td>
            </tr>
        </table>
        <p><input type="submit" value="Добавить" /></p>
        <p>@ViewBag.Status</p>
    </form>
</div>

TestAplication1/Views/UserManager/UserEdit.cshtml
@model TestAplication1.Models.User

<div>
    <h3>Редактирование Id - @Model.Id</h3>
    @using (Html.BeginForm("UserEdit", "UserManager", FormMethod.Post))
    {
        <fieldset>
            @Html.HiddenFor(u => u.Id)
            <p>
                @Html.LabelFor(u => u.Name, "Имя пользователя")
                <br/>
                @Html.EditorFor(u => u.Name)
            </p>
            <p>
                @Html.LabelFor(u => u.Mail, "Почта")
                <br/>
                @Html.EditorFor(u => u.Mail)
            </p>
            <p>
                <input type="submit" value="Сохранить"/>
            </p>
        </fieldset>
    }

    @if (Model.Id > 1)
    {
        var previousId = Model.Id;
        previousId--;
        @Html.ActionLink(" < ", "UserEdit", new {id = previousId})
    }


    <strong>@Model.Id</strong>

    @if (Model.Id < ViewBag.UserCount)
    {
        var nextId = Model.Id;
        nextId++;
        @Html.ActionLink(" > ", "UserEdit", new {id = nextId})
    }
</div>

TestAplication1/Views/UserManager/Users.cshtml
@{
    ViewBag.Title = "Users list";
}

<h2>Список пользователей</h2>
<table>
    <tr>
        <td>
            <p>Id</p>
        </td>
        <td>
            <p>Имя</p>
        </td>
        <td>
            <p>Почта</p>
        </td><td></td>
    </tr>
    @foreach (var u in ViewBag.Users)
    {
        <tr>
            <td>
                <p>@u.Id</p>
            </td>
            <td>
                <p>@u.Name</p>
            </td>
            <td>
                <p>@u.Mail</p>
            </td>
            <td>
                <p>
                    <a href="/UserManager/UserEdit/@u.Id">Редактировать</a>
                </p>
            </td>
        </tr>
    }
</table>